// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Smalldebts.Core.UI.Resources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppStrings {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppStrings() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Smalldebts.Core.UI.Resources.AppStrings", typeof(AppStrings).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string AMano {
            get {
                return ResourceManager.GetString("AMano", resourceCulture);
            }
        }
        
        internal static string LeDebes {
            get {
                return ResourceManager.GetString("LeDebes", resourceCulture);
            }
        }
        
        internal static string LePague {
            get {
                return ResourceManager.GetString("LePague", resourceCulture);
            }
        }
        
        internal static string LePreste {
            get {
                return ResourceManager.GetString("LePreste", resourceCulture);
            }
        }
        
        internal static string MePago {
            get {
                return ResourceManager.GetString("MePago", resourceCulture);
            }
        }
        
        internal static string MePresto {
            get {
                return ResourceManager.GetString("MePresto", resourceCulture);
            }
        }
        
        internal static string TeDebe {
            get {
                return ResourceManager.GetString("TeDebe", resourceCulture);
            }
        }
        
        internal static string NadieTeDebe {
            get {
                return ResourceManager.GetString("NadieTeDebe", resourceCulture);
            }
        }
        
        internal static string ModificaLaDeudaDe {
            get {
                return ResourceManager.GetString("ModificaLaDeudaDe", resourceCulture);
            }
        }
        
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        internal static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        internal static string TeDebeDetail {
            get {
                return ResourceManager.GetString("TeDebeDetail", resourceCulture);
            }
        }
        
        internal static string LeDebesDetail {
            get {
                return ResourceManager.GetString("LeDebesDetail", resourceCulture);
            }
        }
        
        internal static string AManoDetail {
            get {
                return ResourceManager.GetString("AManoDetail", resourceCulture);
            }
        }
        
        internal static string Sort {
            get {
                return ResourceManager.GetString("Sort", resourceCulture);
            }
        }
        
        internal static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        internal static string SortByDate {
            get {
                return ResourceManager.GetString("SortByDate", resourceCulture);
            }
        }
        
        internal static string SortByName {
            get {
                return ResourceManager.GetString("SortByName", resourceCulture);
            }
        }
        
        internal static string SortByBalance {
            get {
                return ResourceManager.GetString("SortByBalance", resourceCulture);
            }
        }
        
        internal static string FilterByPeopleImEvenWith {
            get {
                return ResourceManager.GetString("FilterByPeopleImEvenWith", resourceCulture);
            }
        }
        
        internal static string FilterByPeopleWhoOweMe {
            get {
                return ResourceManager.GetString("FilterByPeopleWhoOweMe", resourceCulture);
            }
        }
        
        internal static string FilterByPeopleIOweTo {
            get {
                return ResourceManager.GetString("FilterByPeopleIOweTo", resourceCulture);
            }
        }
        
        internal static string PeopleIOweOrTheyOweMe {
            get {
                return ResourceManager.GetString("PeopleIOweOrTheyOweMe", resourceCulture);
            }
        }
        
        internal static string FilterAll {
            get {
                return ResourceManager.GetString("FilterAll", resourceCulture);
            }
        }
        
        internal static string NewAmount {
            get {
                return ResourceManager.GetString("NewAmount", resourceCulture);
            }
        }
        
        internal static string AmountFormat {
            get {
                return ResourceManager.GetString("AmountFormat", resourceCulture);
            }
        }
        
        internal static string LastTransactions {
            get {
                return ResourceManager.GetString("LastTransactions", resourceCulture);
            }
        }
        
        internal static string LogginIn {
            get {
                return ResourceManager.GetString("LogginIn", resourceCulture);
            }
        }
        
        internal static string Wait {
            get {
                return ResourceManager.GetString("Wait", resourceCulture);
            }
        }
        
        internal static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        internal static string NoAccButton {
            get {
                return ResourceManager.GetString("NoAccButton", resourceCulture);
            }
        }
        
        internal static string SignUp {
            get {
                return ResourceManager.GetString("SignUp", resourceCulture);
            }
        }
        
        internal static string YesAccButton {
            get {
                return ResourceManager.GetString("YesAccButton", resourceCulture);
            }
        }
        
        internal static string SuccesfulSignUp {
            get {
                return ResourceManager.GetString("SuccesfulSignUp", resourceCulture);
            }
        }
        
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        internal static string PasswordConfirmation {
            get {
                return ResourceManager.GetString("PasswordConfirmation", resourceCulture);
            }
        }
        
        internal static string Debts {
            get {
                return ResourceManager.GetString("Debts", resourceCulture);
            }
        }
        
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        internal static string Reason {
            get {
                return ResourceManager.GetString("Reason", resourceCulture);
            }
        }
        
        internal static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        internal static string ForgottenPasswordButton {
            get {
                return ResourceManager.GetString("ForgottenPasswordButton", resourceCulture);
            }
        }
        
        internal static string SigninIn {
            get {
                return ResourceManager.GetString("SigninIn", resourceCulture);
            }
        }
        
        internal static string SigningUp {
            get {
                return ResourceManager.GetString("SigningUp", resourceCulture);
            }
        }
        
        internal static string EmailConfirmationRequiredText {
            get {
                return ResourceManager.GetString("EmailConfirmationRequiredText", resourceCulture);
            }
        }
        
        internal static string PayDebt {
            get {
                return ResourceManager.GetString("PayDebt", resourceCulture);
            }
        }
        
        internal static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        internal static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        internal static string Acknowledgements {
            get {
                return ResourceManager.GetString("Acknowledgements", resourceCulture);
            }
        }
        
        internal static string Feedback {
            get {
                return ResourceManager.GetString("Feedback", resourceCulture);
            }
        }
        
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        internal static string PrivacyWarning {
            get {
                return ResourceManager.GetString("PrivacyWarning", resourceCulture);
            }
        }
        
        internal static string PrivacyPolicyText {
            get {
                return ResourceManager.GetString("PrivacyPolicyText", resourceCulture);
            }
        }
    }
}
