//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Smalldebts.Core.UI.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Smalldebts.Core.UI.Resources.AppStrings", typeof(AppStrings).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        internal static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are even with .
        /// </summary>
        internal static string AMano {
            get {
                return ResourceManager.GetString("AMano", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are even with .
        /// </summary>
        internal static string AManoDetail {
            get {
                return ResourceManager.GetString("AManoDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:#,##0.##}.
        /// </summary>
        internal static string AmountFormat {
            get {
                return ResourceManager.GetString("AmountFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debts.
        /// </summary>
        internal static string Debts {
            get {
                return ResourceManager.GetString("Debts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        internal static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to all.
        /// </summary>
        internal static string FilterAll {
            get {
                return ResourceManager.GetString("FilterAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to people who I&apos;m even with.
        /// </summary>
        internal static string FilterByPeopleImEvenWith {
            get {
                return ResourceManager.GetString("FilterByPeopleImEvenWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to people who I owe to.
        /// </summary>
        internal static string FilterByPeopleIOweTo {
            get {
                return ResourceManager.GetString("FilterByPeopleIOweTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to people who owe me.
        /// </summary>
        internal static string FilterByPeopleWhoOweMe {
            get {
                return ResourceManager.GetString("FilterByPeopleWhoOweMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transactions.
        /// </summary>
        internal static string LastTransactions {
            get {
                return ResourceManager.GetString("LastTransactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You owe to .
        /// </summary>
        internal static string LeDebes {
            get {
                return ResourceManager.GetString("LeDebes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You owe .
        /// </summary>
        internal static string LeDebesDetail {
            get {
                return ResourceManager.GetString("LeDebesDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I paid her/him.
        /// </summary>
        internal static string LePague {
            get {
                return ResourceManager.GetString("LePague", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I lent him/her.
        /// </summary>
        internal static string LePreste {
            get {
                return ResourceManager.GetString("LePreste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loggin in.
        /// </summary>
        internal static string LogginIn {
            get {
                return ResourceManager.GetString("LogginIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (s)he paid me.
        /// </summary>
        internal static string MePago {
            get {
                return ResourceManager.GetString("MePago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (s)he lent me.
        /// </summary>
        internal static string MePresto {
            get {
                return ResourceManager.GetString("MePresto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify {0}&apos;s debt.
        /// </summary>
        internal static string ModificaLaDeudaDe {
            get {
                return ResourceManager.GetString("ModificaLaDeudaDe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No one owes you, tap here to add someone.
        /// </summary>
        internal static string NadieTeDebe {
            get {
                return ResourceManager.GetString("NadieTeDebe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New amount.
        /// </summary>
        internal static string NewAmount {
            get {
                return ResourceManager.GetString("NewAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t have an account ?.
        /// </summary>
        internal static string NoAccButton {
            get {
                return ResourceManager.GetString("NoAccButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password confirmation.
        /// </summary>
        internal static string PasswordConfirmation {
            get {
                return ResourceManager.GetString("PasswordConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to people who have business with me.
        /// </summary>
        internal static string PeopleIOweOrTheyOweMe {
            get {
                return ResourceManager.GetString("PeopleIOweOrTheyOweMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        internal static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up.
        /// </summary>
        internal static string SignUp {
            get {
                return ResourceManager.GetString("SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort.
        /// </summary>
        internal static string Sort {
            get {
                return ResourceManager.GetString("Sort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to by balance.
        /// </summary>
        internal static string SortByBalance {
            get {
                return ResourceManager.GetString("SortByBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to by update date.
        /// </summary>
        internal static string SortByDate {
            get {
                return ResourceManager.GetString("SortByDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to by name.
        /// </summary>
        internal static string SortByName {
            get {
                return ResourceManager.GetString("SortByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have been succesfully registered, now  you can log in.
        /// </summary>
        internal static string SuccesfulSignUp {
            get {
                return ResourceManager.GetString("SuccesfulSignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  owes you .
        /// </summary>
        internal static string TeDebe {
            get {
                return ResourceManager.GetString("TeDebe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  owes you.
        /// </summary>
        internal static string TeDebeDetail {
            get {
                return ResourceManager.GetString("TeDebeDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait.
        /// </summary>
        internal static string Wait {
            get {
                return ResourceManager.GetString("Wait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait, I already have an account.
        /// </summary>
        internal static string YesAccButton {
            get {
                return ResourceManager.GetString("YesAccButton", resourceCulture);
            }
        }
    }
}
